[S3 Improvements] Reference PR: feature -> develop
CenterForOpenScience/waterbutler pull request #406
Opened 2023-07-26 14:55 UTC by cslzchen

2023-08-08 18:05 UTC, felliott requested changes
There's some confusion in the path math for metadata. It might need some adjustments.  It'd probably also be good to add some tests for metadata listings when the prefix is a bucket subfolder.

2023-08-08 18:05 UTC, felliott commented on waterbutler/providers/s3/provider.py
> +        prefix = self.settings['id'].split(':/')[1] if path == '/' and self.settings.get('id') else path.path
I am pretty sure this is buggy.  The two sides of this `if` statement are not equivalent.  The LHS side is the storage provider prefix.  While WB needs this to send meaningful queries to S3, it is not something that we (directly) expose to the user.  The RHS is the file/folder path that we return to the user in the WB metadata responses.  If the prefix is `/` i.e. not a subfolder, these two things end up being equivalent.  But if the storage provider root folder is a subfolder, e.g. `/foo/`, then the LHS is `/foo/` and the RHS is `/bar/`.

I'm not a 100% convinced I explained this correctly, so maybe an example would be better. On staging, connect a subfolder (for this example, lets call it `blemmo`) of a bucket to a node.  Then fetch the WB metadata listing for the root folder (e.g. `https://files.us.staging.osf.io/v1/resources/mst3k/providers/s3/?meta`). Not only will `blemmo` show up in the file/folder path metadata, but you can get the same response by appending the prefix name to the url (`https://files.us.staging.osf.io/v1/resources/mst3k/providers/s3/blemmo/?meta`).  That's weird.

WB file/folder metadata is defined *relative* to the storage provider prefix.  We treat the prefix as the virtual root. If the prefix is the bucket root folder, then YAY, no extra work for us.  If not, we need to do the path math to make sure our paths are adjusted properly.

2023-08-09 18:47 UTC, felliott commented
I think the thing we need to be looking at for this is the `prepend` kwarg to `WaterButlerPath`.  When building a WBPath object, the first arg is the relative path (`/bar/baz.txt`) and the prepend kwarg is the storage provider root (`/foo/`).  Such a WBPath would represent the file `/foo/bar/baz.txt` on the storage provider, but it's path metadata will be reported as `/bar/baz.txt` since that is the part relative to the project root.  See the owncloud provider for a reference.  owncloud is both path-based and supports subfolder roots and is probably the closest thing to what you want to do here.

The other thing i would recommend is to go ahead and do the `{bucket}:{storage_root}` split in the init method. You can save the results in attributes and refer to them throughout the code.

2023-08-16 13:29 UTC, cslzchen commented
fyi, Johnny's response to CR https://github.com/CenterForOpenScience/waterbutler/pull/409 has been merged as https://github.com/CenterForOpenScience/waterbutler/pull/406/commits/7683994054dd906c7c82afb0159a9be650cfde3c

2023-08-17 23:55 UTC, merged